lexik_jwt_authentication:

    token_ttl: 864000

    # HMAC
    secret_key: Efq5xPmqdUdMCO6jv6XEzEEKGeGjv1GD2xKzM82nfmJjf0uE39OWdwPny8X1
    encoder:
        signature_algorithm: HS256

    # RSA/ECDSA
#    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
#    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
#    pass_phrase: '%env(JWT_PASSPHRASE)%'
