twig:
#  default_path: '%kernel.project_dir%/templates'
  default_path: '%kernel.project_dir%/templates/front'
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  exception_controller: null
  paths:
    '%kernel.project_dir%/templates/admin': admin
  globals:
    breadcrumb: '@App\Service\Breadcrumb'
    searchfilter: '@App\Service\SearchFilter'
    pagination: '@App\Service\Pagination'
    blank_img: 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=='
    frontmenu: '@App\Service\FrontMenu'
  form_themes:
    - '@admin/form_bootstrap.html.twig'             # extends 'bootstrap_4_layout.html.twig'
    - '@admin/form_tetranzselect2entity.html.twig'  # extends '@TetranzSelect2Entity/Form/fields.html.twig'
