vich_uploader:
    db_driver: orm
#    twig: true            # set to false to disable twig integration
    twig: false
#    form: true            # set to false to disable form integration
#    storage: file_system  # or gaufrette or flysystem
    storage: '@App\Form\VichStorage'
#    metadata:
#        auto_detection: true
#        cache: file

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
        vich_images:
#            uri_prefix: '/img'
#            upload_destination: '%kernel.project_dir%/public/img'
            uri_prefix: '%vich.uri_prefix%'
            upload_destination: '%vich.upload_destination%'
            namer: App\Form\VichNamers
            directory_namer: App\Form\VichNamers
