vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
        vich_images:
            uri_prefix: /img
            upload_destination: '%kernel.project_dir%/public/img'
            namer: App\Form\VichNamers
            directory_namer: App\Form\VichNamers
